<?php

namespace ContainerB0XsI6L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorFormService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AuthorForm' shared autowired service.
     *
     * @return \App\Form\AuthorForm
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AuthorForm.php';

        return $container->privates['App\\Form\\AuthorForm'] = new \App\Form\AuthorForm();
    }
}
