<?php

namespace ContainerTbOMRM6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNewQuestionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\NewQuestion' shared autowired service.
     *
     * @return \App\Form\NewQuestion
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/NewQuestion.php';

        return $container->privates['App\\Form\\NewQuestion'] = new \App\Form\NewQuestion();
    }
}
