<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCn8Yc88\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCn8Yc88/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCn8Yc88.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCn8Yc88\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCn8Yc88\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cn8Yc88',
    'container.build_id' => 'c29e4174',
    'container.build_time' => 1632904524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCn8Yc88');
