<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJYjjCUQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJYjjCUQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJYjjCUQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJYjjCUQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJYjjCUQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JYjjCUQ',
    'container.build_id' => '498bb277',
    'container.build_time' => 1634416973,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJYjjCUQ');
