<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB2KkCq6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB2KkCq6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB2KkCq6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB2KkCq6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB2KkCq6\App_KernelDevDebugContainer([
    'container.build_hash' => 'B2KkCq6',
    'container.build_id' => '6c9b743b',
    'container.build_time' => 1634886317,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB2KkCq6');
